# Generated by Django 5.0.6 on 2024-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userextrainfo_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainfo',
            name='iSTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
